version: '3.4'

services:
  microlearn.api.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"

  microlearn.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"


  microlearn.api.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6003:80"


  microlearn.api.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Customers=http://microlearn.api.customers
      - Services__Products=http://microlearn.api.products
    ports:
      - "6004:80"

